# d4void
# adding https with traefik reverse proxy and letsencrypt cert
# adding variable with .env file. See env.example
# adding volume /etc/cron.d /etc/ssmtp and /var/log/apache2 for zoneminder
# docker-compose up -d

version: "3.7"

services:

  traefik:
    restart: "unless-stopped"
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./traefik/dynamic/:/etc/traefik/dynamic:ro"
      - "${VOLDIR}/letsencrypt:/letsencrypt"
      - "${VOLDIR}/traefik-log:/log"
    networks:
      zmnet:
        ipv4_address: ${TRFK_IP}

  zm-db:
    restart: "unless-stopped"
    image: "mariadb:latest"
    container_name: "zm-db"
    networks:
      zmnet:
        ipv4_address: ${ZMDB_IP}
        aliases:
          - "zm-db"
    volumes:
      - "${VOLDIR}/mysql:/var/lib/mysql"
      - "${VOLDIR}/etc/mysql_confd:/etc/mysql/conf.d"
      - type: tmpfs
        target: /dev/shm
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_HOST=%
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  zm:
    restart: "unless-stopped"
    image: "d4void/docker-zoneminder:1.34"
    container_name: "zm"
    depends_on:
      - zm-db
    networks:
      zmnet:
        ipv4_address: ${ZM_IP}
    expose:
      - "80"
    volumes:
      - "${VOLDIR}/cache:/var/cache/zoneminder"
      - "${VOLDIR}/etc/cron.d:/etc/cron.d"
      - "${VOLDIR}/etc/zm:/etc/zm"
      - "${VOLDIR}/etc/ssmtp:/etc/ssmtp"
      - "${VOLDIR}/config:/config"
      - "${VOLDIR}/log:/var/log/zm"
      - "${VOLDIR}/apache2-log:/var/log/apache2/"
      - type: tmpfs
        target: /dev/shm
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ZM_DB_HOST=zm-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.zmcontainer-redirect-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.zmcontainer.middlewares=zmcontainer-redirect-secure"
      - "traefik.http.routers.zmcontainer.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.zmcontainer.entrypoints=web"
      - "traefik.http.routers.zmcontainer-secured.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.zmcontainer-secured.entrypoints=websecure"
      - "traefik.http.routers.zmcontainer-secured.tls=true"
      - "traefik.http.routers.zmcontainer-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.zmcontainer-secured.middlewares=security@file"

networks:
  zmnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
